# Window configuration
[window]
padding = { x = 20, y = 20 }
decorations = "None" # Options: "Full", "None", "Buttonless"
opacity = 0.9
blur = true # Requires a compositor
startup_mode = "Maximized"

# Font configuration
[font]
size = 11.0

[font.normal]
family = "Atkinson Hyperlegible Mono"
style = "Medium"

[font.bold]
family = "Atkinson Hyperlegible Mono"
style = "Bold"

[font.italic]
family = "Atkinson Hyperlegible Mono"
style = "Medium Italic"

[font.bold_italic]
family = "Atkinson Hyperlegible Mono"
style = "Bold Italic"

# Color scheme (Example: Catppuccin Mocha)
[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = '0x1e1e2e'
foreground = '0xcdd6f4'

[colors.cursor]
text = '0x1e1e2e'
cursor = '0xf5e0dc'

[colors.normal]
black = '0x45475a'
red = '0xf38ba8'
green = '0xa6e3a1'
yellow = '0xf9e2af'
blue = '0x89b4fa'
magenta = '0xf5c2e7'
cyan = '0x94e2d5'
white = '0xbac2de'

[colors.bright]
black = '0x585b70'
red = '0xf38ba8'
green = '0xa6e3a1'
yellow = '0xf9e2af'
blue = '0x89b4fa'
magenta = '0xf5c2e7'
cyan = '0x94e2d5'
white = '0xa6adc8'

# Scrolling configuration
[scrolling]
history = 10000 # Maximum lines in scrollback buffer
multiplier = 3 # Lines scrolled per increment

# Cursor configuration
[cursor]
style = { shape = "Block", blinking = "On" }
thickness = 0.15

[mouse]
bindings = [
{ mouse = "Right", action = "Copy" },
]
